### ISSUE TITLE
Issue loading in SPSS file

### ISSUE THREAD

**Issue by LukeBetham** [Quantipy/quantipy3#29] opened 2021-01-13 17:42 UTC
Hi,
I'm having issues loading in an SPSS file using quanitpy. I have quantipy running on python 3.6 and have already tested that I can load the file into notebook using pyreadstat. Not sure why it is erroring here. Any help would be much appreciated!

Code:
`dataset = qp.DataSet("test_dataset")`
`dataset.read_spss('Softlaunch data_CLIENT.sav')`

Error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-ad814a94fb7d> in <module>
      1 dataset = qp.DataSet("test_dataset")
----> 2 dataset.read_spss('Softlaunch data_CLIENT.sav')

~\Anaconda3\lib\site-packages\quantipy\core\dataset.py in read_spss(self, path_sav, **kwargs)
    642         """
    643         if path_sav.endswith('.sav'): path_sav = path_sav.replace('.sav', '')
--> 644         self._meta, self._data = r_spss(path_sav+'.sav', **kwargs)
    645         self._set_file_info(path_sav)
    646         self._rename_blacklist_vars()

~\Anaconda3\lib\site-packages\quantipy\core\tools\dp\io.py in read_spss(path_sav, **kwargs)
    375 def read_spss(path_sav, **kwargs):
    376 
--> 377     meta, data = parse_sav_file(path_sav, **kwargs)
    378     return meta, data
    379 

~\Anaconda3\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in parse_sav_file(filename, path, name, ioLocale, ioUtf8, dichot, dates_as_strings, text_key)
     35     filepath = os.path.abspath(filepath)
     36     data = extract_sav_data(filepath, ioLocale=ioLocale, ioUtf8=ioUtf8)
---> 37     meta, data = extract_sav_meta(filepath, name="", data=data, ioLocale=ioLocale,
     38                                   ioUtf8=ioUtf8, dichot=dichot, dates_as_strings=dates_as_strings,
     39                                   text_key=text_key)

~\Anaconda3\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in extract_sav_meta(sav_file, name, data, ioLocale, ioUtf8, dichot, dates_as_strings, text_key)
    170         # into data, which is immediately prior to the start of the
    171         # dichotomous set columns
--> 172         dls_idx = data.columns.tolist().index(varNames[0])
    173         if metadata.multRespDefs[mrset]['setType'] == 'C':
    174             # Raise if value object of columns is not equal

TypeError: 'map' object is not subscriptable

**Comment by geirfreysson** [comment] 2021-03-04 09:48
Hi Luke.

Sorry for the late reply, I didn't notice this had been raised (so much email - I wish it would just go to my Slack!).

Another user had the same issue here, where I proposed a workaround:
https://github.com/Quantipy/quantipy3/issues/30

If you have a datafile that you can share with me so I could replicate, then we can take a look at fixing this. Until then I suggest the workaround I suggested to Clara (remove the multi-choice definitions in SPSS, read the data, define the multichoice connections again in Quantipy - it's quick work).

Geir

**Comment by geirfreysson** [comment] 2021-03-04 09:48
Closing this as it is a duplicate of https://github.com/Quantipy/quantipy3/issues/30

**Comment by geirfreysson** [comment] 2021-03-04 09:50
Re-opening this as it better describes the issue than the other issue, which I'm closing.

**Suggested workaround:**
The error you are now getting is because the code that reads multiple dichotomy and multiple category sets hasn't been ported properly to python 3.

In the meantime, you could go into SPSS and remove the multi choice definitions (keeping the underlying variables) and read the file into Quantipy (they will become a set of single-choice variables). Then, in Quantipy you can create grids or multi-choice variables from them and it will work just like the SPSS files had been successfully parsed.


```
# we call multi-choice variables delimited sets
dataset.to_delimited_set('q1', 'My multi-choice question', ['q1_1', 'q1_2', 'q1_3']) 
```

![Screen Shot 2021-03-04 at 09 36 13](https://user-images.githubusercontent.com/4630/109945375-12c66b00-7ccf-11eb-9471-31e0fe4ed7f8.png)

**Comment by razvan-cretu** [comment] 2021-03-30 11:23
Hi, 

I am also having the same issue here.

How could I remove the multi choice definitions? I've searched the internet but nothing was helpful.

**Comment by geirfreysson** [comment] 2021-03-30 13:32
Hi @razvan-cretu,

Is the dataset anything you can share with me? Or a dummy version of it that creates the same error?

It's the only way I can test on this and and figure out what's going on.

We could even have an NDA between your organisation and mine if that helps (geir at datasmoothie.com).

**Comment by geirfreysson** [comment] 2021-03-30 13:58
@razvan-cretu, @LukeBetham, I've figured this out and fixed the issue. The tests are running and when they have all past we wil merge a pull request that closes this ticket and fixes the issue.

**Comment by geirfreysson** [comment] 2021-03-31 10:39
Closing this for now. We have added a new .sav file for testing this bug, a fix and a test.

**Closed by geirfreysson** 2021-03-31 10:39 UTC

**Comment by razvan-cretu** [comment] 2021-03-31 13:59
Hi @geirfreysson 

Awesome, thank you so much for the quick fix.

I managed to open the dataset, but I'm getting a couple of different errors now for different datasets..

Here would be the first:

---------------------------------------------------------------------------
SPSSIOError                               Traceback (most recent call last)
<ipython-input-23-2d38145039a7> in <module>
      1 data = qp.DataSet('Example Dataset')
----> 2 data.read_spss(r'C:\Users\razvan.cretu\Downloads\raw export.sav', ioLocale = None)

~\.conda\envs\py37\lib\site-packages\quantipy\core\dataset.py in read_spss(self, path_sav, **kwargs)
    644         """
    645         if path_sav.endswith('.sav'): path_sav = path_sav.replace('.sav', '')
--> 646         self._meta, self._data = r_spss(path_sav+'.sav', **kwargs)
    647         self._set_file_info(path_sav)
    648         self._rename_blacklist_vars()

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\io.py in read_spss(path_sav, **kwargs)
    375 def read_spss(path_sav, **kwargs):
    376 
--> 377     meta, data = parse_sav_file(path_sav, **kwargs)
    378     return meta, data
    379 

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in parse_sav_file(filename, path, name, ioLocale, ioUtf8, dichot, dates_as_strings, text_key)
     34     filepath="{}{}".format(path or '', filename)
     35     filepath = os.path.abspath(filepath)
---> 36     data = extract_sav_data(filepath, ioLocale=ioLocale, ioUtf8=ioUtf8)
     37     meta, data = extract_sav_meta(filepath, name="", data=data, ioLocale=ioLocale,
     38                                   ioUtf8=ioUtf8, dichot=dichot, dates_as_strings=dates_as_strings,

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in extract_sav_data(sav_file, ioLocale, ioUtf8)
     42 def extract_sav_data(sav_file, ioLocale='en_US.UTF-8', ioUtf8=True):
     43     """ see parse_sav_file doc """
---> 44     with sr.SavReader(sav_file, returnHeader=True, ioLocale=ioLocale, ioUtf8=ioUtf8) as reader:
     45         thedata = [x for x in reader]
     46         header = thedata[0]

~\.conda\envs\py37\lib\site-packages\savReaderWriter\savReader.py in __init__(self, savFileName, returnHeader, recodeSysmisTo, verbose, selectVars, idVar, rawMode, ioUtf8, ioLocale)
     73         self.nCases = self.numberofCases
     74 
---> 75         self.myStruct = self.getStruct(self.varTypes, self.varNames)
     76         self.unpack_from = self.myStruct.unpack_from
     77         self.seekNextCase = self.spssio.spssSeekNextCase

~\.conda\envs\py37\lib\site-packages\savReaderWriter\generic.py in getStruct(self, varTypes, varNames, mode)
    307           contained in the SPSS data file (mode is "ab" or "rb" or "cp")"""
    308         if mode in (b"ab", b"rb", b"cp"):   # derive endianness from file
--> 309             endianness = self.releaseInfo["big/little-endian code"]
    310             endianness = ">" if endianness > 0 else "<"
    311         elif mode == b"wb":                 # derive endianness from host

~\.conda\envs\py37\lib\site-packages\savReaderWriter\generic.py in releaseInfo(self)
    243         relInfoArr = (c_int * len(relInfo))()
    244         retcode = self.spssio.spssGetReleaseInfo(c_int(self.fh), relInfoArr)
--> 245         checkErrsWarns("Problem getting ReleaseInfo", retcode)
    246         info = dict([(item, relInfoArr[i]) for i, item in enumerate(relInfo)])
    247         return info

~\.conda\envs\py37\lib\site-packages\savReaderWriter\error.py in checkErrsWarns(msg, retcode)
    116     msg += " [%s]" % retcodes.get(retcode, retcode)
    117     if retcode > 0:
--> 118         raise SPSSIOError(msg, retcode)
    119     elif retcode < 0:
    120         warnings.warn(msg, SPSSIOWarning, stacklevel=2)

SPSSIOError: Problem getting ReleaseInfo [SPSS_NO_TYPE73]

I am using SPSS 26, but wierd how I managed to open some of the datasets and others I couldn't open

This would be the second one:

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-24-f26bf5061f49> in <module>
      1 data = qp.DataSet('Example Dataset')
----> 2 data.read_spss(r'C:\Users\razvan.cretu\Downloads\2101634.sav', ioLocale = None)

~\.conda\envs\py37\lib\site-packages\quantipy\core\dataset.py in read_spss(self, path_sav, **kwargs)
    644         """
    645         if path_sav.endswith('.sav'): path_sav = path_sav.replace('.sav', '')
--> 646         self._meta, self._data = r_spss(path_sav+'.sav', **kwargs)
    647         self._set_file_info(path_sav)
    648         self._rename_blacklist_vars()

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\io.py in read_spss(path_sav, **kwargs)
    375 def read_spss(path_sav, **kwargs):
    376 
--> 377     meta, data = parse_sav_file(path_sav, **kwargs)
    378     return meta, data
    379 

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in parse_sav_file(filename, path, name, ioLocale, ioUtf8, dichot, dates_as_strings, text_key)
     34     filepath="{}{}".format(path or '', filename)
     35     filepath = os.path.abspath(filepath)
---> 36     data = extract_sav_data(filepath, ioLocale=ioLocale, ioUtf8=ioUtf8)
     37     meta, data = extract_sav_meta(filepath, name="", data=data, ioLocale=ioLocale,
     38                                   ioUtf8=ioUtf8, dichot=dichot, dates_as_strings=dates_as_strings,

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in extract_sav_data(sav_file, ioLocale, ioUtf8)
     43     """ see parse_sav_file doc """
     44     with sr.SavReader(sav_file, returnHeader=True, ioLocale=ioLocale, ioUtf8=ioUtf8) as reader:
---> 45         thedata = [x for x in reader]
     46         header = thedata[0]
     47         dataframe = pd.DataFrame.from_records(thedata[1:], coerce_float=False)

~\.conda\envs\py37\lib\site-packages\quantipy\core\tools\dp\spss\reader.py in <listcomp>(.0)
     43     """ see parse_sav_file doc """
     44     with sr.SavReader(sav_file, returnHeader=True, ioLocale=ioLocale, ioUtf8=ioUtf8) as reader:
---> 45         thedata = [x for x in reader]
     46         header = thedata[0]
     47         dataframe = pd.DataFrame.from_records(thedata[1:], coerce_float=False)

~\.conda\envs\py37\lib\site-packages\savReaderWriter\savReader.py in _items(self, start, stop, step, returnHeader)
    227                 record = self.selector(record)
    228                 record = [record] if len(record) == 1 else list(record)
--> 229             record = self.formatValues(record)
    230             yield record
    231 

~\.conda\envs\py37\lib\site-packages\savReaderWriter\savReader.py in formatValues(self, record)
    189                 value = value[:varType]
    190                 if self.ioUtf8_:
--> 191                     record[i] = value.decode("utf-8")
    192                 else:
    193                     record[i] = value

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xef in position 254: unexpected end of data

Let me know if I should open a separate issue for these, since it is still a loading issue I thought here might be ok.

Thanks once again for your commitment. This package is really helpful.

All the best!

**Comment by geirfreysson** [comment] 2021-04-01 08:49
I’m not sure what the first issue is, it looks like it’s related to savReaderWriter, which we use to read spss files. If you can somehow replicate the error with the Example (A).sav file that is in the tests folder, then we can investiage.

The second error is most likely because of locale issues. Are the datasets that aren’t working in a language that doesn’t use utf-8 encoding? Have you tried sending information about the encoding to the reader?

We’ve done more tests using Utf8 than other locales, but you can try sending these parameters to read_spss:

```
ioLocale="en_US.UTF-8"
ioUtf8=True
```
The default locale is US English, utf-8, but you can try passing another locale to the reader.

**Comment by razvan-cretu** [comment] 2021-04-01 10:06
I've tried with both of the parameters and still nothing.

I think this is because some of the open ends from the data as I saw some respondents answer with weird characters inside the textboxes. The dataset is in English but I think some respondents answered with Chinese characters in some of the textboxes.

Is there a locale for Chinese ?

Thank you once again for your help!  :)

**Comment by geirfreysson** [comment] 2021-04-01 10:37
We have come across this as well, and we’ve solved it by removing the open ended questions in SPSS before processing in Quantipy. If the SPSS document is encoded as UTF8 (this can be configured in SPSS) we should be able to read it.

I think we need to open a new ticket, like “some non-english characters in open ended questions cause SPSS read failure”.
