### ISSUE TITLE
Error using read_spss

### ISSUE THREAD

**Issue by clarakheinz** [Quantipy/quantipy3#30] opened 2021-03-03 00:13 UTC
Hello, 

Attempted to use quantipy and read in a sav file. Received this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/dataset.py", line 644, in read_spss
    self._meta, self._data = r_spss(path_sav+'.sav', **kwargs)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/tools/dp/io.py", line 377, in read_spss
    meta, data = parse_sav_file(path_sav, **kwargs)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/tools/dp/spss/reader.py", line 36, in parse_sav_file
    data = extract_sav_data(filepath, ioLocale=ioLocale, ioUtf8=ioUtf8)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/tools/dp/spss/reader.py", line 44, in extract_sav_data
    with sr.SavReader(sav_file, returnHeader=True, ioLocale=ioLocale, ioUtf8=ioUtf8) as reader:
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/savReader.py", line 57, in __init__
    ioUtf8, ioLocale)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/header.py", line 31, in __init__
    super(Header, self).__init__(savFileName, ioUtf8, ioLocale)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/generic.py", line 35, in __init__
    self.spssio = self.loadLibrary()
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/generic.py", line 117, in loadLibrary
    spssio = self._loadLibs("macos")
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/generic.py", line 89, in _loadLibs
    return [load(os.path.join(path, lib)) for lib in libs][-1]
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/generic.py", line 89, in <listcomp>
    return [load(os.path.join(path, lib)) for lib in libs][-1]
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/spssio/macos/libicuuc48.1.dylib, 6): Library not loaded: @executable_path/../lib/libicudata48.1.dylib
  Referenced from: /Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/savReaderWriter/spssio/macos/libicuuc48.1.dylib
  Reason: image not found

My environment specs:
Name          |          Version          |         Build  Channel
------------|-------------------|--------------------
ca-certificates     | 2021.1.19         |   hecd8cb5_0  
certifi         |          2020.12.5    |    py36hecd8cb5_0  
chardet               |    4.0.0          |          pypi_0    pypi
decorator          |       4.4.2         |           pypi_0    pypi
ftfy                    |  5.5.1                 |   pypi_0    pypi
idna                     | 2.10                 |    pypi_0    pypi
importlib-metadata |       3.7.0     |               pypi_0    pypi
libcxx                  |  10.0.0               |         1  
libedit                |   3.1.20191231     |    h1de35cc_1  
libffi                  |  3.3                 | hb1e8313_2  
lxml                  |    4.6.2              |      pypi_0    pypi
ncurses                |   6.2              |    h0a44026_1  
numpy                  |   1.14.5           |        pypi_0    pypi
openssl               |    1.1.1j              | h9ed2024_0  
pandas               |     0.25.3            |       pypi_0    pypi
pillow                 |   8.1.1                   | pypi_0    pypi
pip                     |  21.0.1           | py36hecd8cb5_0  
prettytable           |    2.1.0         |           pypi_0    pypi
python                 |   3.6.13          |     h88f2d9e_0  
python-dateutil  |         2.8.1        |            pypi_0    pypi
python-pptx      |         0.6.18        |           pypi_0    pypi
pytz                   |   2021.1             |      pypi_0    pypi
quantipy3          |       0.2.3          |          pypi_0    pypi
readline             |     8.1                 | h9ed2024_0  
requests           |       2.25.1            |       pypi_0    pypi
scipy                |     1.2.1                   | pypi_0    pypi
setuptools       |         52.0.0          | py36hecd8cb5_0  
six                    |   1.15.0                  | pypi_0    pypi
sqlite              |      3.33.0             |  hffcf06c_0  
tk                   |     8.6.10              | hb0a8c7a_0  
typing-extensions  |       3.7.4.3  |                pypi_0    pypi
urllib3            |       1.26.3              |     pypi_0    pypi
watchdog     |             2.0.2            |        pypi_0    pypi
wcwidth       |            0.2.5               |     pypi_0    pypi
wheel          |           0.36.2          |   pyhd3eb1b0_0  
xlsxwriter   |             1.3.7             |       pypi_0    pypi
xmltodict   |              0.12.0           |        pypi_0    pypi
xz              |          5.2.5               | h1de35cc_0  
zipp          |            3.4.0               |     pypi_0    pypi
zlib          |            1.2.11              | h1de35cc_3  

My code:
```
import quantipy as qp
dataset = qp.DataSet("Test")
dataset.read_spss('Data.sav')
```

**Comment by geirfreysson** [comment] 2021-03-03 20:51
Hi Clara.

Setting up the savReaderWriter library is often the trickiest part of starting to use Quantipy. If you check out [the documentation for the library](https://pythonhosted.org/savReaderWriter/), it mentions that Mac users should make sure to export the location of the libraries that are doing the reading, like so

`export DYLD_LIBRARY_PATH=/Library/Python/3.6/site-packages/savReaderWriter/spssio/macos`

replacing the above path with the location of your library.

Let me know if that didn't work.

**Comment by clarakheinz** [comment] 2021-03-03 23:43
Hi Geir,

I am sorry I missed the key step for Mac OS in the documentatio. I completed the export as suggested and tried my code again. There was a different error this time:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/dataset.py", line 644, in read_spss
    self._meta, self._data = r_spss(path_sav+'.sav', **kwargs)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/tools/dp/io.py", line 377, in read_spss
    meta, data = parse_sav_file(path_sav, **kwargs)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/tools/dp/spss/reader.py", line 39, in parse_sav_file
    text_key=text_key)
  File "/Users/ckheinz/Miniconda/miniconda3/envs/envqp/lib/python3.6/site-packages/quantipy/core/tools/dp/spss/reader.py", line 172, in extract_sav_meta
    dls_idx = data.columns.tolist().index(varNames[0])
TypeError: 'map' object is not subscriptable
```

**Comment by geirfreysson** [comment] 2021-03-04 09:39
Hi Clara.

The error you are now getting is because the code that reads multiple dichotomy and multiple category sets hasn't been ported properly to python 3.

Can you share the datafile with us in some way that removes sensitve information from it? Then we could use the datafile to fix it.

In the meantime, you could go into SPSS and remove the multi choice definitions (keeping the underlying variables) and read the file into Quantipy (they will become  a set of single-choice variables). Then, in Quantipy you can create grids or multi-choice variables from them and it will work just like the SPSS files had been successfully parsed.

```
# we call multi-choice variables delimited sets
dataset.to_delimited_set('q1', 'My multi-choice question', ['q1_1', 'q1_2', 'q1_3']) 
```

![Screen Shot 2021-03-04 at 09 36 13](https://user-images.githubusercontent.com/4630/109943505-2e307680-7ccd-11eb-9c06-a198b178bf7f.png)

**Comment by geirfreysson** [comment] 2021-03-04 09:51
Closing this as it is a duplicate of https://github.com/Quantipy/quantipy3/issues/29

**Closed by geirfreysson** 2021-03-04 09:51 UTC

**Comment by geirfreysson** [comment] 2021-03-31 10:42
> There was a different error this time:

A fix for this has been released, @clarakheinz. Upgrade to version 0.2.5.

**Comment by clarakheinz** [comment] 2021-04-22 19:02
Thank you! I apologize, I did not get a chance to let you know I was unable to provide a sample of anonymized data for solving the issue. Appreciate the update!

**Comment by geirfreysson** [comment] 2021-04-23 08:43
You're very welcome. Fully understand that people don't have datasets lying around they can share.
